### PR TITLE
Simply serialisation format of inner objects

### PR DESCRIPTION
**Pull request by sestegra**
On the wire, data structure are pure JSON.

### CODE REVIEW

**Comment by lejard-h** [comment]
Nice, do you plan other big change or can I do a release ?

**Comment by sestegra** [comment]
You can release now. I will work only this week-end.
I found out that `List<DateTime>` and `Map<String,Class>` can't be deserialize as expected.

**Comment by lejard-h** [comment]
On this pull request ?

**Comment by sestegra** [comment]
I will continue to work only on it starting this Sunday. Feel free to release this first step before.
I don't know yet if I will find shortly a solution for the open points on complex List and Map.

**Pull request closed without merging**
